# Generated by Django 3.1.6 on 2021-02-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20210205_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_added'], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='brief_desription',
            field=models.CharField(default='', max_length=150, verbose_name='Brief Description'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cats',
            field=models.ManyToManyField(blank=True, to='pages.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=60, unique=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='brief_desription',
            field=models.CharField(default='', max_length=150, verbose_name='Brief Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
    ]
