# Generated by Django 3.1.6 on 2021-02-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210205_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='desription',
            new_name='description',
        ),
    ]
