# Generated by Django 3.1.6 on 2021-02-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210211_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
    ]
